#!/usr/bin/env bash

set -e

DIRNAME=$(dirname $0)
COOKIE_PATH="$DIRNAME/cookie.jar"
CURL_CMD="curl --location --silent --cookie $COOKIE_PATH --cookie-jar $COOKIE_PATH"

source "$DIRNAME/settings.ini"

[[ $1 = "min" ]] && OFFER="$OFFER_MIN" || OFFER="$OFFER_NORM"

# # #

$CURL_CMD\
    -d "IDToken1=$LOGIN"\
    -d "IDToken2=$PASSWORD"\
    -d "goto=https://my.yota.ru/selfcare/loginSuccess"\
    -d "org=customer"\
    https://login.yota.ru/UI/Login > /dev/null

productId=$($CURL_CMD https://my.yota.ru/selfcare/devices | grep -Eo 'name="product" value="[0-9]+"' | grep -Eo '[0-9]+')

[[ -z $productId ]] && echo "Не могу получить productId!" && exit 1

# TODO: всамоделешнее подтверждение переключения
isOfferChanged=$($CURL_CMD\
    -d "product=$productId"\
    -d "offerCode=$OFFER"\
    -d "areOffersAvailable=false"\
    -d "status=custom"\
    -d "isSlot=false"\
    -d "currentDevice=1"\
    -d "isDisablingAutoprolong=false"\
    https://my.yota.ru/selfcare/devices/changeOffer | grep -o "offerDisabled")

[[ -z $isOfferChanged ]] && echo "Не могу переключить тариф!" && exit 2
